### ISSUE TITLE
Reference to svn-win32-libintl.zip no longer valid

### ISSUE THREAD

**Issue by k10blogger** [jelmer/subvertpy#30]
Going through the document cant seem to find the following as Tigris no longer online:

> Install SVN libintl. http://subversion.tigris.org/servlets/ProjectDocumentList?folderID=2627 Download svn-win32-libintl.zip. extract it to the directory that you want.

Can this be updated to reflect more recent location?

**Comment by jelmer** [comment]
As far as I am aware there isn't a more recent location; this is the URL used in the instructions from Subversion itself: https://svn.apache.org/repos/asf/subversion/trunk/INSTALL

**Comment by k10blogger** [comment]
How is then the subvertpy is being built on windows? I am stuck at providing the environment variable SVN_LIBINTL.
Do you have a workaround?

**Comment by jelmer** [comment]
That's really a question about building Subversion rather than Subvertpy.

Let me just drop this section and point at the upstream instructions. Apparently the intl library is optional, so that should at least allow you to build without intl support.

**Comment by jelmer** [comment]
You'd probably be interested in #32, which is about publishing wheels.

**Comment by k10blogger** [comment]
Yeah i saw that. Let me work on that. I requested for a copy from Tigeris i am waiting for their response. 
I dont see the issue number #32 are you referring to #28 ?

**Comment by jelmer** [comment]
Sorry, yes - I meant #28. 

I don't think there is much value in the current code in setup.py specific to Windows, especially since it hardcodes some of the flags in setup.py for specific Subversion versions - and it hasn't been updated for anything since svn 1.7.

Let me remove that workflow from setup.py, and drop the Windows-specific instructions from the README since they're out of date - bad instructions are worse than no instructions. I believe building on Windows should still work if you set the right flags, but I'm going to leave building Subversion and setting the right environment variables as an exercise to the reader for the moment. 

Hopefully this will all be less relevant anyway once appveyor can publish wheels anyway. Let's move the conversation about that to #28.
